from .forgot_password_menu import ForgotPasswordMenu
from .game_mode_menu import GameModeMenu
from .introductory_quiz_menu import IntroductoryQuizMenu
from .log_in_menu import LogInMenu
from .reset_password_menu import ResetPasswordMenu
from .settings_menu import SettingsMenu
from .sign_up_menu import SignUpMenu
from .specs_menu import SpecsMenu
from .statistics_menu import StatisticsMenu
